apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: barista
spec:
  template:
    spec:
      containers:
      - name: user-container
        image: homework-nexus-registry.apps.shared-na46.openshift.opentlc.com/v7nh9-barista:prod-2022-02-26-16-38-20

