apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-shop-pipeline
  namespace: v7nh9-argocd
spec:
  destination:
    namespace: v7nh9-pipeline
    server: https://kubernetes.default.svc
  project: coffee-shop
  source:
    path: ./coffee-shop-pipeline
    repoURL: http://homework-gitea.gpte-hw-cicd.svc:3000/ncamilli-redhat.com-v7nh9/coffee-shop-final-lab.git
    targetRevision: HEAD
