apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-shop-pipeline
  namespace: GUID-argocd
spec:
  destination:
    namespace: GUID-pipeline
    server: https://kubernetes.default.svc
  project: coffee-shop
  source:
    path: ./coffee-shop-pipeline
    repoURL: http://homework-gitea.gpte-hw-cicd.svc:3000/OCP_USERNAME-GUID/coffee-shop-final-lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
