apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  template:
    spec:
      containers:
      - name: coffee-shop
        image: homework-nexus-registry.apps.shared-na46.openshift.opentlc.com/v7nh9-coffee-shop:prod-2022-02-25-11-24-52

