---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: coffee-shop-binding
spec:
  params:
  - name: git-repo-url
    value: http://homework-gitea.gpte-hw-cicd.svc:3000/$(body.repository.full_name)
  - name: git-revision
    value: $(body.after)
