apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: barista-template
spec:
  params:
  - name: git-repo-url
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: coffee-shop-pipeline-
    spec:
      params:
      - name: PREFIX
        value: v7nh9
      - name: APP_NAME
        value: barista
      - name: SOURCE_GIT_URL
        value: $(tt.params.git-repo-url)
      - name: SOURCE_GIT_REVISION
        value: $(tt.params.git-revision)
      - name: SOURCE_GIT_CONTEXT_DIR
        value: barista
      - name: KUSTOMIZE_GIT_URL
        value: http://homework-gitea.gpte-hw-cicd.svc:3000/ncamilli-redhat.com-v7nh9/coffee-shop-final-lab.git
      - name: KUSTOMIZE_GIT_REVISION
        value: master
      - name: KUSTOMIZE_GIT_CONTEXT_DIR
        value: coffee-shop-kustomize/barista
      - name: KUSTOMIZE_GIT_FILE_NAME
        value: overlays/production/deployment-patches.yaml
      - name: MAVEN_MIRROR_URL
        value: http://homework-nexus.gpte-hw-cicd.svc:8081/repository/maven-all-public/
      - name: NEXUS_REGISTRY_URL
        value: homework-nexus-registry.apps.shared-na46.openshift.opentlc.com
      - name: NAMESPACE_DEV
        value: v7nh9-dev-coffeeshop
      - name: DEPLOY_SERVERLESS
        value: "true"
      pipelineRef:
        name: build-and-deploy-quarkus-application
      workspaces:
      - name: app-source
        persistentVolumeClaim:
          claimName: workspace-pvc
      - name: maven-settings
        emptyDir: {}
      - name: images-url
        emptyDir: {}
